name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install Robot Framework and SeleniumLibrary
      run: |
        source .venv/bin/activate
        pip install robotframework robotframework-seleniumlibrary

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Verify Chrome installation
      run: chrome --version

    - name: Run Robot Framework tests
      run: |
        source .venv/bin/activate
        robot --outputdir results test.robot