name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        # Add other dependencies if needed, e.g., robotframework-seleniumlibrary
        

    - name: Run Robot Framework tests
      run: |
        robot test.robot
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-results
        path: results/
